name: Deployment

on:
  push:
    tags:
      - "*.*.*.*"

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Executing Remote SSH Commands Using Password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME}}
          password: ${{ secrets.SSH_PASSWORD}}
          port: 22
          command_timeout: 1337m
          script_stop: true
          script: |
            cd ${{ secrets.REPOSITORY_LOCATION }}
            git pull origin master --force
            docker compose -f docker-compose.prod.yml stop
            docker compose -f docker-compose.prod.yml build
            docker compose -f docker-compose.prod.yml up -d
            docker image prune --force
            docker container prune --force
            docker builder prune --force